version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my_network

  migrate:
    build:
      context: ./database
    container_name: prisma-migrate
    command: bash -c "npx prisma generate && npx prisma migrate deploy"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./database/prisma:/usr/src/app/prisma
      - ./database/prisma/client:/usr/src/app/node_modules/@prisma/client
    networks:
      - my_network

  # NATS Service
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - '4222:4222'
      - '8222:8222'
    networks:
      - my_network

  # Gateway Service
  gateway:
    build: ./api-gateway
    container_name: gateway
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: '123'
      DATABASE_NAME: microservices
      NATS_URL: nats://nats:4222
    ports:
      - '3000:3000'
    networks:
      - my_network
    depends_on:
      - migrate

  # Reader Microservice
  sdf
  reader-mgt:
    build: ./reader-mgt
    container_name: reader-service
    volumes:
      - ./database/prisma:/usr/src/app/prisma 
      sdf
      - ./database/prisma/client:/usr/src/app/node_modules/@prisma/client
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: '123'
      DATABASE_NAME: microservices
      NATS_URL: nats://nats:4222
    networks:
      - my_network
    depends_on:
      - migrate

  # Article Microservice
  article-mgt:
    build: ./article-mgt
    container_name: article-service
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: '123'
      DATABASE_NAME: microservices
      NATS_URL: nats://nats:4222
    networks:
      - my_network
    depends_on:
      - migrate

networks:
  my_network:
    driver: bridge

volumes:
  postgres:
  prisma-client:
